version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - qdrant
    env_file:
      - .env
    environment:
      RABBITMQ_CONNECTION_URL: amqp://user:password@rabbitmq:5672/
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333   
      LLM_SHERPA_URL: http://llmsherpa:5001/api/parseDocument?renderFormat=all&useNewIndentParser=true
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # HTTP API port
      - "6334:6334" # gRPC API port
    networks:
      - app-network
    volumes:
      - qdrant_storage:/qdrant/storage
  
  llmsherpa:
    image: ghcr.io/nlmatics/nlm-ingestor
    ports:
      - "5010:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
  qdrant_storage:
