version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Forward host port 8001 to container port 8000
    volumes:
      - .:/app # Mount local code for live updates
    depends_on:
      - rabbitmq
      - qdrant
    env_file:
      - .env
    environment:
      RABBITMQ_CONNECTION_URL: amqp://user:password@rabbitmq:5672/
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6335
      LLM_SHERPA_URL: http://llmsherpa:5011/api/parseDocument?renderFormat=all&useNewIndentParser=true
      APP_MODE: DEVELOPMENT
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5673:5672" # Forward host port 5673 to container AMQP port 5672
      - "15673:15672" # Forward host port 15673 to container management port 15672
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6335:6333" # Forward host port 6335 to container HTTP API port 6333
      - "6336:6334" # Forward host port 6336 to container gRPC API port 6334
    networks:
      - app-network
  llmsherpa:
    image: ghcr.io/nlmatics/nlm-ingestor
    ports:
      - "5011:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
